import { useEffect, useState } from 'react'

const api = async (path, options) => { const res = await fetch(path, options); const data = await res.json(); if (!res.ok) throw new Error(data.detail || 'Request failed'); return data }

export default function App() {
  const [page, setPage] = useState('Dashboard'), [health, setHealth] = useState(), [documents, setDocuments] = useState([]), [error, setError] = useState('')
  const refresh = async () => { try { const [h, d] = await Promise.all([api('/health'), api('/documents')]); setHealth(h); setDocuments(d) } catch (e) { setError(e.message) } }
  useEffect(() => { refresh() }, [])
  const pages = [['Dashboard','Overview'],['Documents','Documents & Ingestion'],['Retrieve','Retrieval Inspector'],['Ask','Ask Tickets'],['Traces','Week 5 Error Analysis']]
  return <div className="app-shell"><aside><div className="brand"><p className="eyebrow">ASK MY TICKETS</p><h2>Knowledge hub</h2><span>Weeks 1–5</span></div><nav>{pages.map(([key,label]) => <button className={page===key?'active':''} onClick={()=>setPage(key)} key={key}><span className="nav-dot" />{label}</button>)}</nav><div className="sidebar-note"><b>Current flow</b><p>Ingest → retrieve → answer → analyse failures</p></div></aside><main><header><p className="eyebrow">{page === 'Traces' ? 'WEEK 5 · EVALS & ERROR ANALYSIS' : 'RAG WORKBENCH'}</p><h1>{page === 'Dashboard' ? 'Support knowledge assistant' : pages.find(([key])=>key===page)?.[1]}</h1><p>{page === 'Dashboard' ? 'Ingest documents, inspect evidence, answer safely, and review failures.' : 'Use the sidebar to move through the complete RAG workflow.'}</p></header>{error&&<p className="error">{error}</p>}{page==='Dashboard'&&<Dashboard health={health} documents={documents} setPage={setPage}/>} {page==='Documents'&&<Documents documents={documents} refresh={refresh} error={setError}/>} {page==='Retrieve'&&<Retrieve error={setError}/>} {page==='Ask'&&<Ask error={setError}/>} {page==='Traces'&&<Traces error={setError}/>}</main></div>
}
function Dashboard({health,documents,setPage}) { const chunks=documents.reduce((n,d)=>n+d.chunk_count,0); return <section><div className="metrics"><article className="metric"><span>Indexed documents</span><strong>{documents.length}</strong><small>Ready for retrieval</small></article><article className="metric"><span>Knowledge chunks</span><strong>{chunks}</strong><small>Sentence-aware segments</small></article><article className="metric"><span>App health</span><strong>{health?.status || '…'}</strong><small>Embedding, Qdrant, provider</small></article></div><article className="card workflow"><div><p className="eyebrow">YOUR WORKFLOW</p><h2>From support documents to evidence-backed answers</h2><p>Each screen exposes one step of the system, so you can inspect what happens before trusting an answer.</p></div><div className="workflow-steps">{[['1','Documents','Add and index source files','Documents'],['2','Retrieve','See the chunks found for a question','Retrieve'],['3','Ask','Generate a cited answer or a refusal','Ask'],['4','Analyse','Read traces and rank failures','Traces']].map(([number,title,copy,target])=><button onClick={()=>setPage(target)} key={title}><span>{number}</span><b>{title}</b><small>{copy}</small></button>)}</div></article><article className="card"><h2>Quick start</h2><ol><li>Upload or review the support-ticket source documents.</li><li>Use Retrieval Inspector to validate the evidence returned.</li><li>Ask a customer question and confirm the source citations.</li><li>For Week 5, sample about 20 traces and open-code failures before grouping them.</li></ol></article></section> }
function Documents({documents,refresh,error}) { const [file,setFile]=useState(),[busy,setBusy]=useState(false);const upload=async e=>{e.preventDefault();if(!file)return;setBusy(true);try{const data=new FormData();data.append('file',file);await api('/upload',{method:'POST',body:data});await refresh();setFile()}catch(err){error(err.message)}finally{setBusy(false)}};return <section className="card"><h2>Documents & ingestion</h2><p>Upload TXT, MD, DOCX, PDF, or XLSX. The current index is rebuilt from all files.</p><form onSubmit={upload} className="upload"><input type="file" accept=".txt,.md,.docx,.pdf,.xlsx" onChange={e=>setFile(e.target.files[0])}/><button disabled={!file||busy}>{busy?'Ingesting…':'Upload and ingest'}</button></form><div className="documents">{documents.map(doc=><article key={doc.filename}><b>{doc.filename}</b><span>{doc.chunk_count} chunks</span><p>{doc.preview}</p></article>)}</div></section> }
function Retrieve({error}) { const [question,setQuestion]=useState(''),[chunks,setChunks]=useState([]);const submit=async e=>{e.preventDefault();try{setChunks(await api('/retrieve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,top_k:3})}))}catch(err){error(err.message)}};return <section className="card"><h2>Retrieval inspector</h2><p>Week 2 semantic search: inspect the ticket chunks before generation.</p><form onSubmit={submit}><label>Question<textarea required value={question} onChange={e=>setQuestion(e.target.value)}/></label><button>Inspect retrieval</button></form><Evidence chunks={chunks}/></section> }
function Ask({error}) { const [question,setQuestion]=useState(''),[result,setResult]=useState();const submit=async e=>{e.preventDefault();try{setResult(await api('/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,top_k:3})}))}catch(err){error(err.message)}};return <section className="card"><h2>Grounded answer</h2><p>Week 3: a weak match is refused before the LLM is called.</p><form onSubmit={submit}><label>Customer question<textarea required value={question} onChange={e=>setQuestion(e.target.value)}/></label><button>Generate answer</button></form>{result&&<div className="answer"><h3>{result.skipped_llm?'No relevant evidence':'Answer'}</h3><p>{result.answer}</p><p><b>Sources:</b> {result.sources.join(', ')||'None'}</p><small>Trace: {result.trace_id}</small></div>}</section> }
function Traces({error}) { const [traces,setTraces]=useState([]),[selected,setSelected]=useState();const load=async()=>{try{setTraces(await api('/traces?limit=50'))}catch(e){error(e.message)}};useEffect(()=>{load()},[]);const open=async id=>{try{setSelected(await api(`/traces/${id}`))}catch(e){error(e.message)}};const chunks=selected?.stages.find(s=>s.name==='retrieval')?.data.chunks??[];return <section className="card"><div className="row"><div><h2>Week 5 trace review</h2><p>Open-code a failure before naming its category.</p></div><button onClick={load}>Refresh</button></div><div className="trace-list">{traces.map(t=><button className="trace" onClick={()=>open(t.trace_id)} key={t.trace_id}><b>{t.question}</b><span>{t.outcome}</span></button>)}</div>{selected&&<div className="detail"><h3>{selected.question}</h3><p>{selected.answer||selected.error}</p><Evidence chunks={chunks}/></div>}</section> }
function Evidence({chunks}) { return chunks.length?<ol className="evidence">{chunks.map(c=><li key={`${c.source}-${c.chunk_index}`}><b>{c.source} · chunk {c.chunk_index}</b><small>distance {Number(c.distance).toFixed(3)}</small><p>{c.text}</p></li>)}</ol>:null }
